# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'
# private pod source.
source 'https://github.com/CocoaPods/Specs.git'

target 'WalletDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'

end



